name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container: gableroux/unity3d:2019.3.9f1
    steps:
        - name: Checkout Project
          uses: actions/checkout@v1

        - name: Decrypt the license file
          run: openssl aes-256-cbc -d -in .github/Unity_v2019.x.ulf.enc -k ${{ secrets.UNITY_LICENSE_DECRYPT_KEY }} >> .github/Unity_v2019.x.ulf
        
        # Activate unity
        - name: Activate Unity
          run: /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile -manualLicenseFile .github/Unity_v2019.x.ulf || exit 0
        
        
        # Create a folder to store apk
        - name : Create a folder to store apk
          run: 'mkdir --parents results/artifacts'
    
        
        
        
        # Build Windows and OSX
        - name: Build Android Player
          run: /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -noUpm -logFile -projectPath . -Android ./CISample.apk
       # - name: Build OSX Player
        #  run: /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -noUpm -logFile -projectPath . -buildOSXUniversalPlayer ./bin-osx/CISample.app      
        
        
        #- name : create floder next action
        #  run: 'env | grep GITHUB_ | sort > results/artifacts/ci-env.txt'
        
        - name: Archive Android Build
          uses: actions/upload-artifact@v1
          with:
            name: AndroidApk
            path: results/artifacts/                  #https://github.com/sravanudutha/ApkRepository/blob/master            #../bin-win64

      #  - name: Archive Mac Build
       #   uses: actions/upload-artifact@v1
        #  with:
         #   name: CISampleOSXBinary
          #  path: ./bin-osx
